### ISSUE TITLE
Timeouts

### ISSUE THREAD

**Issue by joemensor** [mpmc/HS602#2]
The code works well to retrieve the ip address of the HS602 on the network but fails with a timeout with the first 'proper' command that is sent (as below) 

 msg = bytes([67, ip[0], ip[1], ip[2], ip[3]])

Any ideas? I've increased the timeout, but this obviously doesn't help, so I'm not entirely sure what is going on.

**Comment by mpmc** [comment]
@joemensor Really sorry for not seeing this sooner!

Can you tell me if:

* You've updated the firmware, if so what version?
* What brand/model of the box you have?
* Have you tried setting the addr variable?
* Can you paste the error output?
```
dev = HS602('192.168.1.100')
```

**Comment by joemensor** [comment]
OK, so it turns out that the above command does work, but it appears that the 'is_streaming' function simply times out...it does find the HS602 though...

Traceback (most recent call last):
  File "/home/pi/hs602/bottle.py", line 993, in _handle
    out = route.call(**args)
  File "/home/pi/hs602/bottle.py", line 1984, in wrapper
    rv = callback(*a, **ka)
  File "web.py", line 36, in status
    streaming = box.is_streaming()
  File "/home/pi/hs602/HS602.py", line 364, in is_streaming
    r = self.send(bytes(cmd))
  File "/home/pi/hs602/HS602.py", line 167, in send
    self.connect()
  File "/home/pi/hs602/HS602.py", line 124, in connect
    data, source = self.udp(bytes("HS602").encode('utf-8'))
  File "/home/pi/hs602/HS602.py", line 111, in udp
    data, source = s.recvfrom(2048)
timeout: timed out

I have the HS602-t but it is branded as StarTech.com, so perhaps something is different in terms of the firmware? How can I determine what version of the firmware I have and is this something I can flash anyway?

**Comment by mpmc** [comment]
Does the Android and/or ShareView software work normally? Really I'd need access to test it.

**Comment by joemensor** [comment]
Hi. yeah, the Android and ShareView apps work. Interestingly I created a small app in C# using sockets to toggle the streaming and it works fine, the code is basically the same, weird.

**Comment by mpmc** [comment]
It's weird, very weird. I've just tested it & on mine it's fine..

```
>>> from HS602 import HS602
>>> f = HS602()
>>> f.is_streaming()
True
```

**Comment by joemensor** [comment]
Thanks for the replies....I've gotten to the bottom of this....turns out the problem was my version of Python. For whatever reason I was running 2.6.3 of Python and it was causing lockups on the HS602 as the TCP recv-q was simply building up. Anyway, all is good now, thanks for your help!

**Comment by mpmc** [comment]
Ah, I see. I'll add version checking.

But, if you want to help improve my code, please feel free :)
